# Generated by Django 3.2.8 on 2021-12-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_medial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('instagram', 'Instagram'), ('facebook-f', 'Facebook'), ('twitter', 'Twitter'), ('vk', 'VKontakte'), ('pinterest', 'Pinterest'), ('whatsapp', 'WhatsApp'), ('youtube', 'YouTube'), ('google', 'Google')], max_length=30, verbose_name='Social media')),
                ('url', models.URLField(unique=True, verbose_name='Social media url')),
            ],
        ),
    ]
