# Generated by Django 3.2.8 on 2022-01-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlog_app', '0004_aboutme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='text',
            new_name='text1',
        ),
    ]
